#!/usr/bin/env python3
"""Convert the publishable subset of the Obsidian vaults into docs/.

One-way: the vaults are the editing home, docs/notes/ is generated output. Run
after editing notes, then commit the result.

    python3 scripts/sync_vault.py            # convert
    python3 scripts/sync_vault.py --check    # report drift, write nothing
    python3 scripts/sync_vault.py --section networks

Exit codes:
    0  clean
    1  drift (--check only)
    2  policy violation — a denylisted path or a private-info pattern
    3  refused to clobber a file that isn't ours

The policy gate is the point of this script. Emission is two-phase — render
everything, verify everything, only then write — so a violation anywhere leaves
no partial output behind.

Stdlib only (tomllib needs Python >= 3.11).
"""

from __future__ import annotations

import argparse
import fnmatch
import re
import shutil
import sys
import tomllib
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = Path(__file__).resolve().parent / "vault_manifest.toml"

MARKER_PREFIX = "<!-- AUTOGENERATED by scripts/sync_vault.py from "
MARKER = (
    MARKER_PREFIX + '"{src}". DO NOT EDIT — edit the vault note and re-run: '
    "python3 scripts/sync_vault.py -->"
)

IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp"}

# Live Obsidian vaults. We convert the in-repo copies (they're what's committed
# against), but if iCloud is ahead the copies are stale and the run would
# publish yesterday's notes. Warn; don't block — staying out of the way of the
# editing workflow matters more than being right about which copy is newer.
ICLOUD = Path.home() / "Library/Mobile Documents/iCloud~md~obsidian/Documents"
ICLOUD_TWINS = {"Computer Science copy": "Computer Science", "spring2026 copy": "spring2026"}


class PolicyViolation(Exception):
    """A denylisted path or private-info pattern reached the emit stage."""


class ClobberRefused(Exception):
    """Output path exists and wasn't written by us."""


# ── Obsidian → Material callout mapping ──────────────────────────────────────
# Material renders `!!!` static, `???` collapsed, `???+` collapsible-but-open.
# The trailing `-` on `> [!question]-` is what makes the Q&A cards collapse, so
# the fold suffix is load-bearing, not decoration.
CALLOUT_TYPES = {
    "note": "note", "info": "info", "tip": "tip", "warning": "warning",
    "danger": "danger", "question": "question", "example": "example",
    "abstract": "abstract", "success": "success", "bug": "bug", "quote": "quote",
    "failure": "failure", "hint": "tip", "todo": "info", "caution": "warning",
    "attention": "warning", "error": "danger", "summary": "abstract",
    "faq": "question",
    "important": "tip",   # closest Material colour/semantic
    "goal": "success",    # invented in the vault; no Material equivalent
}

CALLOUT_HEAD = re.compile(
    r"^(?P<indent>(?:> ?)*)> ?\[!(?P<type>[\w-]+)\](?P<fold>[+-]?) ?(?P<title>.*)$"
)
EMBED = re.compile(r"!\[\[(?P<target>[^\]|]+?)(?:\|(?P<mod>[^\]]+))?\]\]")
WIKILINK = re.compile(
    r"(?<!!)\[\[(?P<target>[^\]|#]+?)(?:#(?P<head>[^\]|]+))?(?:\|(?P<alias>[^\]]+))?\]\]"
)
PARENT_CHILD = re.compile(r"^(?P<kind>Parent|Children):\s*(?P<rest>.+)$")
# Accepts the malformed single-bracket `Children: [RadixSort]` in the CS vault.
LINKISH = re.compile(r"\[\[?([^\]\[]+?)\]?\]")
FENCE = re.compile(r"^\s*(`{3,}|~{3,})")
TABLE_ROW = re.compile(r"^\s*\|.*\|\s*$")


@dataclass
class Note:
    src: Path            # absolute path in the vault
    rel: str             # vault-relative, for reporting and the marker
    section: "Section"
    frontmatter: dict = field(default_factory=dict)
    body: str = ""
    out: Path | None = None


@dataclass
class Section:
    title: str
    slug: str
    vault_root: Path
    vault_name: str
    include: list[str]
    strip_headings: list[str] = field(default_factory=list)
    strip_heading_prefixes: list[str] = field(default_factory=list)
    rewrite: list[list[str]] = field(default_factory=list)
    scrub_regex: list[str] = field(default_factory=list)
    drop_lines_matching: list[str] = field(default_factory=list)
    renumber: bool = False
    debox: bool = False


@dataclass
class Report:
    warnings: list[str] = field(default_factory=list)
    skipped_empty: list[str] = field(default_factory=list)
    dead_links: list[str] = field(default_factory=list)
    orphan_images: list[str] = field(default_factory=list)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)


# ── helpers ──────────────────────────────────────────────────────────────────

def slugify(name: str) -> str:
    """`06 Giant Component` -> `06-giant-component`.

    The numeric prefix is kept on purpose: with it, alphabetical order is the
    intended order, so nav needs no separate ordering metadata and URLs survive
    a title rename. Strip it here if the URLs ever read badly — the prefix would
    then have to become a nav sort key.
    """
    name = unicodedata.normalize("NFKD", name)
    name = name.replace("&", " and ")
    name = re.sub(r"[^\w\s-]", " ", name, flags=re.UNICODE)
    name = re.sub(r"[\s_]+", "-", name.strip().lower())
    return re.sub(r"-{2,}", "-", name).strip("-") or "untitled"


def split_frontmatter(text: str) -> tuple[dict, str]:
    """Parse just enough YAML for `title:` and a `tags:` list. No pyyaml."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw, body = text[3:end], text[end + 4:]
    fm: dict = {}
    key = None
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^(\w[\w-]*):\s*(.*)$", line)
        if m:
            key = m.group(1)
            val = m.group(2).strip()
            if val.startswith("[") and val.endswith("]"):
                fm[key] = [v.strip().strip("'\"") for v in val[1:-1].split(",") if v.strip()]
            elif val:
                fm[key] = val.strip("'\"")
            else:
                fm[key] = []
        elif line.lstrip().startswith("- ") and key:
            if not isinstance(fm.get(key), list):
                fm[key] = []
            fm[key].append(line.lstrip()[2:].strip().strip("'\""))
    return fm, body.lstrip("\n")


def in_fence(lines: list[str], idx: int) -> bool:
    depth = 0
    for line in lines[:idx]:
        if FENCE.match(line):
            depth ^= 1
    return bool(depth)


# ── pipeline ─────────────────────────────────────────────────────────────────

def apply_patches(body: str, patch: dict, rep: Report, rel: str) -> str:
    if not patch:
        return body
    for pat in patch.get("scrub_regex", []):
        body = re.sub(pat, "", body)
    for name in patch.get("drop_embeds", []):
        before = body
        body = re.sub(r"^.*!\[\[" + re.escape(name) + r"\]\].*$\n?", "", body, flags=re.M)
        if body != before:
            rep.warn(f"{rel}: dropped embed of denylisted image {name!r}")
    for col in patch.get("drop_table_columns", []):
        body = drop_table_column(body, col)
    if patch.get("drop_lines"):
        lines = body.splitlines()
        kill: set[int] = set()
        for start, end in patch["drop_lines"]:
            kill.update(range(start - 1, end))
        body = "\n".join(l for i, l in enumerate(lines) if i not in kill)
    return body


def drop_table_column(body: str, header: str) -> str:
    """Remove a named column from every pipe table that has one."""
    out, col = [], None
    for line in body.splitlines():
        if not TABLE_ROW.match(line):
            out.append(line)
            col = None
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if col is None:
            if header not in cells:
                out.append(line)
                continue
            col = cells.index(header)
        if col < len(cells):
            cells.pop(col)
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def strip_headings(body: str, headings: list[str], prefixes: list[str] | None = None) -> str:
    """Drop a section: its heading through to the next same-or-higher heading.

    `prefixes` catches sections whose whole title is a homework problem, e.g.
    `## HW8 P1: Direct (overlap-method) proof of MC convergence`. Those can't be
    matched exactly — the title varies per file — but the prefix is the tell.
    """
    prefixes = prefixes or []
    if not headings and not prefixes:
        return body
    lines = body.splitlines()
    out, skip_to = [], None
    for i, line in enumerate(lines):
        if skip_to is not None:
            m = re.match(r"^(#{1,6})\s", line)
            if m and len(m.group(1)) <= skip_to and not in_fence(lines, i):
                skip_to = None
            else:
                continue
        stripped = line.strip()
        hit = None
        if not in_fence(lines, i):
            if any(stripped == h.strip() for h in headings):
                hit = stripped
            elif any(stripped.startswith(p) for p in prefixes):
                hit = stripped
        if hit:
            level = re.match(r"^(#{1,6})", hit)
            if level is None:
                # Both patterns bound a section by its heading level, so a match on
                # a non-heading has no end to find and would swallow the rest of the
                # note. Only reachable via a manifest entry that forgot its hashes.
                raise SystemExit(
                    f"strip pattern matched a non-heading line: {hit!r}\n"
                    "  strip_headings / strip_heading_prefixes must name headings."
                )
            skip_to = len(level.group(1))
            continue
        out.append(line)
    return "\n".join(out)


def renumber_headings(body: str) -> str:
    """Close the gap left by a stripped section.

    The networks notes number their sections ("## 6. Important lemmas"), so
    removing section 7 leaves 1-6 then 8, which advertises the removal. Renumber
    to run consecutively.
    """
    lines = body.splitlines()
    n = 0
    out = []
    for i, line in enumerate(lines):
        m = re.match(r"^## (\d+)\.\s+(.*)$", line)
        if m and not in_fence(lines, i):
            n += 1
            out.append(f"## {n}. {m.group(2)}")
        else:
            out.append(line)
    result = "\n".join(out)
    return result + "\n" if body.endswith("\n") else result


def fix_defects(body: str, rep: Report, rel: str) -> str:
    """Repair the specific breakages the vaults are known to contain."""
    # A 4+ backtick fence is a typo unless it wraps a nested ``` block.
    if "````" in body and "```\n" not in body.replace("````", ""):
        body = body.replace("````", "```")
        rep.warn(f"{rel}: normalised a 4-backtick fence")

    # Embeds glued to the end of a list item: `parent(k) = k/2![[Heap array.png]]`.
    body, n = re.subn(r"(\S)(!\[\[)", r"\1 \2", body)
    if n:
        rep.warn(f"{rel}: separated {n} embed(s) glued to preceding text")

    # U+2212 MINUS SIGN inside math breaks TeX; leave it alone in prose.
    def fix_minus(m: re.Match) -> str:
        return m.group(0).replace("−", "-")
    body = re.sub(r"\$\$?[^$]+\$\$?", fix_minus, body)

    # An empty ```mermaid block renders as an error box.
    body, n = re.subn(r"^```mermaid\s*\n\s*(?:graph \w+\s*\n)?\s*```\s*$\n?", "", body, flags=re.M)
    if n:
        rep.warn(f"{rel}: dropped {n} empty mermaid block(s)")

    # Truncated file: an odd number of fences means one never closed.
    if sum(1 for l in body.splitlines() if FENCE.match(l)) % 2:
        body = body.rstrip("\n") + "\n```\n"
        rep.warn(f"{rel}: closed an unterminated code fence")
    return body


def convert_table_math(body: str) -> str:
    """`$$..$$` in a table cell doesn't render under arithmatex; inline does."""
    return "\n".join(
        re.sub(r"\$\$(.+?)\$\$", r"$\1$", line) if TABLE_ROW.match(line) else line
        for line in body.splitlines()
    )


def debox_tasks(body: str) -> str:
    """`- [ ] x` -> `- x`.

    In the ML notes the checkboxes are a study artifact wrapped around real
    content, not a to-do list. Published as checkboxes they read as unfinished.
    """
    return re.sub(r"^(\s*[-*])\s*\[[ xX]\]\s+", r"\1 ", body, flags=re.M)


def convert_callouts(body: str, rep: Report, rel: str) -> str:
    lines = body.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        m = CALLOUT_HEAD.match(lines[i])
        if not m or in_fence(lines, i):
            out.append(lines[i])
            i += 1
            continue

        depth = m.group("indent").count(">")
        raw_type = m.group("type").lower()
        mapped = CALLOUT_TYPES.get(raw_type)
        title = m.group("title").strip()
        if mapped is None:
            mapped = "note"
            title = title or raw_type.title()
            rep.warn(f"{rel}: unknown callout type {raw_type!r} -> note")
        elif raw_type == "goal" and not title:
            title = "Goal"

        fold = m.group("fold")
        kw = "???" if fold == "-" else ("???+" if fold == "+" else "!!!")

        pad = "    " * depth
        out.append(f'{pad}{kw} {mapped} "{title}"' if title else f"{pad}{kw} {mapped}")

        # Body: every following line one `>` deeper than the head's indent.
        i += 1
        strip = re.compile(r"^(?:> ?){%d}" % (depth + 1))
        while i < len(lines) and strip.match(lines[i]):
            inner = strip.sub("", lines[i])
            out.append(f"{pad}    {inner}" if inner.strip() else "")
            i += 1
        out.append("")
    return "\n".join(out)


def lift_parent_children(body: str, rel: str) -> tuple[str, list[tuple[str, str]]]:
    """Pull `Parent:`/`Children:` off the top of the body.

    These lines are how the CS vault encodes hierarchy (it has no frontmatter).
    Returned as (kind, target) pairs so the caller can resolve them to links
    once it knows what actually got published.
    """
    lines = body.splitlines()
    rels: list[tuple[str, str]] = []
    keep, consumed = [], 0
    for i, line in enumerate(lines):
        if i - consumed > 3:
            keep.extend(lines[i:])
            break
        m = PARENT_CHILD.match(line.strip())
        if m:
            for target in LINKISH.findall(m.group("rest")):
                rels.append((m.group("kind"), target.strip()))
            consumed += 1
            continue
        keep.append(line)
    else:
        pass
    return "\n".join(keep).lstrip("\n"), rels


def lift_leading_tag(body: str, fm: dict) -> tuple[str, dict]:
    """A bare `#java` on line 1 is how the CS vault tags notes."""
    lines = body.splitlines()
    if lines and re.fullmatch(r"#[\w/-]+(\s+#[\w/-]+)*", lines[0].strip()):
        tags = [t.lstrip("#") for t in lines[0].split()]
        fm.setdefault("tags", [])
        if isinstance(fm["tags"], list):
            fm["tags"].extend(tags)
        return "\n".join(lines[1:]).lstrip("\n"), fm
    return body, fm


def ensure_title(fm: dict, note: Note) -> tuple[dict, str]:
    """Give every page exactly one H1, with a consistent title.

    Two shapes to reconcile. The networks notes have no H1 at all (frontmatter,
    then straight into `## 1.`); the ML notes lead with `# 09 Transformers &
    Attention`. Left alone that yields "Giant Component" next to "09
    Transformers & Attention" in the same nav.

    The numeric prefix earns its place in the *filename* (it makes alphabetical
    order the intended order) but not in the heading, where the sidebar already
    conveys sequence. So strip it from the title and synthesise an H1 when the
    note lacks one.
    """
    body = note.body
    m = re.search(r"^#\s+(.+)$", body, flags=re.M)
    if not fm.get("title"):
        raw = m.group(1).strip() if m else Path(note.rel).stem.replace("_", " ")
        fm["title"] = re.sub(r"^\d+[.\s]+", "", raw).strip()
    if m:
        body = body.replace(m.group(0), f"# {fm['title']}", 1)
    else:
        body = f"# {fm['title']}\n\n{body}"
    return fm, body


# ── asset + link resolution ──────────────────────────────────────────────────

class AssetRegistry:
    """Copies only the images that a published note actually references."""

    def __init__(self, dest: Path):
        self.dest = dest
        self.copies: dict[Path, str] = {}   # source -> emitted filename
        self.referenced: set[Path] = set()

    def add(self, src: Path) -> str:
        if src in self.copies:
            return self.copies[src]
        name = f"{slugify(src.stem)}{src.suffix.lower()}"
        # Distinct sources can slugify identically; keep both.
        taken = set(self.copies.values())
        if name in taken:
            n = 2
            while f"{slugify(src.stem)}-{n}{src.suffix.lower()}" in taken:
                n += 1
            name = f"{slugify(src.stem)}-{n}{src.suffix.lower()}"
        self.copies[src] = name
        self.referenced.add(src)
        return name

    def flush(self, rep: Report) -> None:
        self.dest.mkdir(parents=True, exist_ok=True)
        for src, name in self.copies.items():
            target = self.dest / name
            if not target.exists() or target.stat().st_size != src.stat().st_size:
                shutil.copy2(src, target)
            size = src.stat().st_size
            if size > 500_000:
                rep.warn(f"{name}: {size/1e6:.1f}MB — consider recompressing in the vault")


def build_name_index(vault_roots: dict[str, Path]) -> dict[str, list[Path]]:
    """Casefolded basename -> paths. Mirrors Obsidian's own link resolution."""
    index: dict[str, list[Path]] = {}
    for root in vault_roots.values():
        if not root.exists():
            continue
        for p in root.rglob("*"):
            if not p.is_file() or "/.obsidian/" in str(p) or "/.git/" in str(p):
                continue
            for key in {p.stem.casefold(), p.name.casefold()}:
                index.setdefault(key, []).append(p)
    return index


def pick(candidates: list[Path], origin: Path, target: str, rep: Report, rel: str) -> Path:
    """Same dir, then shallowest, then alphabetical. Warn if it was a guess."""
    if len(candidates) == 1:
        return candidates[0]
    ranked = sorted(candidates, key=lambda p: (p.parent != origin.parent, len(p.parts), str(p)))
    rep.warn(f"{rel}: [[{target}]] is ambiguous ({len(candidates)} matches); chose {ranked[0].name}")
    return ranked[0]


def convert_embeds(note: Note, index, assets: AssetRegistry, deny, rep: Report) -> str:
    def repl(m: re.Match) -> str:
        target = m.group("target").strip()
        cands = index.get(target.casefold(), [])
        if not cands:
            rep.dead_links.append(f"{note.rel}: embed ![[{target}]] — no such file")
            return ""
        src = pick(cands, note.src, target, rep, note.rel)
        if src.suffix.lower() not in IMAGE_SUFFIXES:
            rep.warn(f"{note.rel}: non-image embed ![[{target}]] -> link (no transclusion)")
            return f"[{target}]({target})"
        # An embed of a denylisted image is a violation, not a skip. This is what
        # keeps the answer screenshots out even though a note embeds them.
        if is_denied(src, deny):
            raise PolicyViolation(
                f"{note.rel} embeds denylisted image {rel_to_repo(src)!r}. "
                f"Add a [[patch]] drop_embeds entry or remove the embed."
            )
        name = assets.add(src)
        alt = re.sub(r"\s+at\s+\d.*$", "", src.stem).replace("_", " ").strip()
        rel_path = relpath_from(note.out, Path("docs/assets/images") / name)
        return f"![{alt}]({rel_path})"
    return EMBED.sub(repl, note.body)


def resolve_wikilinks(note: Note, index, published: dict[Path, Path], rep: Report) -> str:
    def repl(m: re.Match) -> str:
        target = m.group("target").strip()
        alias = (m.group("alias") or "").strip()
        head = (m.group("head") or "").strip()
        label = alias or target
        cands = index.get(target.casefold(), [])
        if not cands:
            rep.dead_links.append(f"{note.rel}: [[{target}]] — no such note")
            return label
        src = pick(cands, note.src, target, rep, note.rel)
        out = published.get(src)
        if out is None:
            # Resolved but not published: denylisted, out of manifest, or empty.
            # Degrade to plain text so the page reads fine and --strict stays green.
            rep.dead_links.append(f"{note.rel}: [[{target}]] — not published, now plain text")
            return label
        link = relpath_from(note.out, out)
        if head:
            link += "#" + slugify(head)
        return f"[{label}]({link})"
    return WIKILINK.sub(repl, note.body)


def relpath_from(src_page: Path, target: Path) -> str:
    import posixpath
    return posixpath.relpath(target.as_posix(), src_page.parent.as_posix())


def rel_to_repo(p: Path) -> str:
    try:
        return str(p.relative_to(REPO))
    except ValueError:
        return str(p)


# ── the gate ─────────────────────────────────────────────────────────────────

def is_denied(path: Path, deny: list[str]) -> bool:
    rel = rel_to_repo(path)
    return any(fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch("/" + rel, pat) for pat in deny)


def find_violations(rendered: str, src_rel: str, patterns: list[re.Pattern]) -> list[str]:
    """Every policy hit in one file, as human-readable strings.

    Reports the pattern and location but never the matched text — echoing it
    would copy the private string into scrollback and CI logs.
    """
    hits = []
    for i, line in enumerate(rendered.splitlines(), 1):
        for pat in patterns:
            if pat.search(line):
                # Line numbers are into the RENDERED page, not the source note —
                # transforms have already added and removed lines by this point.
                # Say so, or you go hunting at the wrong line in the vault.
                hits.append(f"{src_rel} -> output line {i}: matches /{pat.pattern}/")
    return hits


def assert_publishable(rendered: str, src_rel: str, patterns: list[re.Pattern]) -> None:
    hits = find_violations(rendered, src_rel, patterns)
    if hits:
        raise PolicyViolation(hits[0])


# ── emit ─────────────────────────────────────────────────────────────────────

def render(note: Note) -> str:
    """Frontmatter FIRST, then the marker.

    YAML frontmatter is only frontmatter if it opens the file. Put anything
    above it — even an HTML comment — and MkDocs parses the whole block as body
    text, so `title:`/`tags:` are ignored and the page prints its own metadata
    as visible content. `mkdocs build --strict` won't catch it: the output is
    valid markdown, just wrong.
    """
    fm = {k: v for k, v in note.frontmatter.items() if k in ("title", "tags") and v}
    lines: list[str] = []
    if fm:
        lines.append("---")
        # title first: it's the line a human looks for.
        for k in ("title", "tags"):
            v = fm.get(k)
            if not v:
                continue
            if isinstance(v, list):
                lines.append(f"{k}:")
                lines.extend(f"  - {item}" for item in v)
            else:
                lines.append(f"{k}: {v}")
        lines.append("---")
    lines.append(MARKER.format(src=note.rel))
    lines.append("")
    body = re.sub(r"\n{3,}", "\n\n", note.body).strip("\n")
    lines.append(body)
    return "\n".join(lines).rstrip("\n") + "\n"


def is_ours(path: Path) -> bool:
    if not path.exists():
        return True
    try:
        return MARKER_PREFIX in path.read_text(encoding="utf-8")[:400]
    except (UnicodeDecodeError, OSError):
        return False


def load_manifest(path: Path) -> dict:
    with path.open("rb") as fh:
        return tomllib.load(fh)


def collect(cfg: dict, only: list[str] | None, rep: Report) -> tuple[list[Note], dict, list[str]]:
    roots = {v["name"]: REPO / v["root"] for v in cfg["vault"]}
    deny = cfg["denylist"]["paths"]
    notes: list[Note] = []

    for sc in cfg["section"]:
        if only and sc["slug"] not in only:
            continue
        section = Section(
            title=sc["title"], slug=sc["slug"], vault_name=sc["vault"],
            vault_root=roots[sc["vault"]], include=sc["include"],
            strip_headings=sc.get("strip_headings", []),
            strip_heading_prefixes=sc.get("strip_heading_prefixes", []),
            rewrite=sc.get("rewrite", []),
            scrub_regex=sc.get("scrub_regex", []),
            drop_lines_matching=sc.get("drop_lines_matching", []),
            renumber=sc.get("renumber_headings", False),
            debox=sc.get("debox", False),
        )
        if not section.vault_root.exists():
            rep.warn(f"vault {section.vault_name!r} not found at {section.vault_root} — skipped")
            continue
        seen: set[Path] = set()
        for pattern in section.include:
            matches = sorted(section.vault_root.glob(pattern))
            if not matches:
                rep.warn(f"[{section.slug}] include {pattern!r} matched nothing")
            for src in matches:
                if src in seen or not src.is_file():
                    continue
                seen.add(src)
                # An include that selects a denylisted path is a manifest bug.
                # Stop the run; do not quietly skip it.
                if is_denied(src, deny):
                    raise PolicyViolation(
                        f"[{section.slug}] include {pattern!r} selects denylisted "
                        f"path {rel_to_repo(src)!r} — the manifest contradicts itself"
                    )
                notes.append(Note(src=src, rel=rel_to_repo(src), section=section))
    return notes, roots, deny


def warn_if_stale(roots: dict, rep: Report) -> None:
    """The repo copies are what we convert; iCloud is where Obsidian writes."""
    for copy_name, live_name in ICLOUD_TWINS.items():
        live, copy = ICLOUD / live_name, REPO / copy_name
        if not (live.exists() and copy.exists()):
            continue
        newer = [
            p for p in live.rglob("*.md")
            if ".obsidian" not in str(p)
            and (copy / p.relative_to(live)).exists()
            and p.stat().st_mtime > (copy / p.relative_to(live)).stat().st_mtime + 2
        ]
        if newer:
            rep.warn(
                f"{copy_name!r} is behind the live iCloud vault ({len(newer)} newer file(s), "
                f"e.g. {newer[0].name!r}). Converting the repo copy anyway — re-copy if that's wrong."
            )


def build_nav(notes: list[Note], cfg: dict, only: list[str] | None) -> list[str]:
    """Emit the nav block, nesting sections under an optional `group`.

    A section with `group = "Programming"` lands two levels deep
    (Programming > Python > note); one without stays top-level. Consecutive
    sections sharing a group share the parent heading, so manifest order is
    nav order.
    """
    lines: list[str] = []
    by_slug: dict[str, list[Note]] = {}
    for n in notes:
        by_slug.setdefault(n.section.slug, []).append(n)

    current_group: str | None = None
    for sc in cfg["section"]:
        group = by_slug.get(sc["slug"])
        if not group:
            continue
        parent = sc.get("group")
        if parent != current_group:
            if parent:
                lines.append(f"  - {parent}:")
            current_group = parent
        indent = "      " if parent else "  "
        lines.append(f"{indent}- {sc['title']}:")
        for n in sorted(group, key=lambda x: x.out.name):
            title = n.frontmatter.get("title", n.out.stem)
            lines.append(f"{indent}    - {title}: {n.out.relative_to('docs').as_posix()}")
    return lines


def splice_nav(nav_lines: list[str], check: bool) -> bool:
    path = REPO / "mkdocs.yml"
    text = path.read_text(encoding="utf-8")
    begin = "  # BEGIN GENERATED NAV"
    end = "  # END GENERATED NAV"
    bi, ei = text.find(begin), text.find(end)
    if bi == -1 or ei == -1:
        raise SystemExit("mkdocs.yml: nav sentinels missing — refusing to guess where nav goes")
    head = text[: text.index("\n", bi) + 1]
    new = head + ("\n".join(nav_lines) + "\n" if nav_lines else "") + text[ei:]
    if new != text and not check:
        path.write_text(new, encoding="utf-8")
    return new != text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    ap.add_argument("--force", action="store_true", help="overwrite files we didn't generate")
    ap.add_argument("--section", action="append", help="only this section slug (repeatable)")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    cfg = load_manifest(MANIFEST)
    rep = Report()
    patterns = [re.compile(p, re.I) for p in cfg["denylist"]["fail_patterns"]]
    patches = {p["file"]: p for p in cfg.get("patch", [])}
    docs_root = REPO / cfg["output"]["docs_root"]
    assets = AssetRegistry(REPO / cfg["output"]["assets_dir"])

    notes, roots, deny = collect(cfg, args.section, rep)
    warn_if_stale(roots, rep)
    index = build_name_index(roots)

    # Pass 1: parse, transform, decide output paths.
    rewrite_hits: dict[tuple[str, str], int] = {}
    for n in notes:
        text = n.src.read_text(encoding="utf-8")
        n.frontmatter, n.body = split_frontmatter(text)
        n.body = apply_patches(n.body, patches.get(n.rel, {}), rep, n.rel)
        n.body = strip_headings(n.body, n.section.strip_headings,
                                n.section.strip_heading_prefixes)
        for pat in n.section.drop_lines_matching:
            n.body = re.sub(rf"^.*{pat}.*$\n?", "", n.body, flags=re.M)
        # Targeted rewrites first: where removing a citation would break the
        # sentence around it, name the replacement rather than letting a regex
        # guess. Only then the generic scrub, which handles the cases where the
        # citation is a self-contained parenthetical.
        #
        # Hits are tallied across the whole section, not per file: a rewrite
        # targets one sentence in one note, so warning per-file would emit one
        # line for every other note and bury the warnings that matter. What's
        # worth knowing is a rewrite that matched nothing ANYWHERE — that means
        # a vault edit moved out from under it.
        for pat, sub in n.section.rewrite:
            n.body, k = re.subn(pat, sub, n.body)
            rewrite_hits[(n.section.slug, pat)] = rewrite_hits.get((n.section.slug, pat), 0) + k
        for pat in n.section.scrub_regex:
            n.body = re.sub(pat, "", n.body)
        if n.section.renumber:
            n.body = renumber_headings(n.body)
        n.body = fix_defects(n.body, rep, n.rel)
        n.body = convert_table_math(n.body)
        if n.section.debox:
            n.body = debox_tasks(n.body)
        n.body = convert_callouts(n.body, rep, n.rel)
        n.body, n._rels = lift_parent_children(n.body, n.rel)
        n.body, n.frontmatter = lift_leading_tag(n.body, n.frontmatter)
        n.frontmatter, n.body = ensure_title(n.frontmatter, n)
        n.out = docs_root.relative_to(REPO) / n.section.slug / f"{slugify(Path(n.rel).stem)}.md"

    # A rewrite that never fired anywhere means the vault text it targeted has
    # changed or gone. Surface it: silently skipping is how a citation sneaks
    # back in behind a rule that no longer applies.
    for (slug, pat), k in rewrite_hits.items():
        if k == 0:
            rep.warn(f"[{slug}] rewrite {pat!r} matched nothing in any note — stale rule?")

    # Drop notes with no content left. They're linked from real notes, so the
    # resolver below degrades those links rather than publishing blank pages.
    live = []
    for n in notes:
        if not re.sub(r"^#.*$", "", n.body, flags=re.M).strip():
            rep.skipped_empty.append(n.rel)
        else:
            live.append(n)
    notes = live
    published = {n.src: n.out for n in notes}

    # Pass 2: resolve links now that we know what exists.
    for n in notes:
        n.body = convert_embeds(n, index, assets, deny, rep)
        n.body = resolve_wikilinks(n, index, published, rep)
        if getattr(n, "_rels", None):
            crumbs = []
            for kind, target in n._rels:
                cands = index.get(target.casefold(), [])
                out = published.get(cands[0]) if cands else None
                crumbs.append(
                    f"[{target}]({relpath_from(n.out, out)})" if out else target
                )
            n.body = f"**Related:** {' · '.join(crumbs)}\n\n{n.body}"

    # Pass 3: render + verify EVERYTHING before writing ANYTHING. A violation
    # in the last note must not leave the first thirty on disk.
    rendered = [(n, render(n)) for n in notes]
    violations: list[str] = []
    for n, text in rendered:
        violations.extend(find_violations(text, n.rel, patterns))
    if violations:
        # Report every hit, not just the first. Fixing these means editing vault
        # sources or adding manifest rules, and doing that one-at-a-time across
        # 18 files is how you give up and weaken the patterns instead.
        raise PolicyViolation(
            f"{len(violations)} hit(s) across "
            f"{len({v.split(' -> ')[0] for v in violations})} file(s):\n    "
            + "\n    ".join(violations)
        )

    # Pass 4: write.
    changed, wrote = [], 0
    for n, text in rendered:
        dest = REPO / n.out
        if not is_ours(dest) and not args.force:
            raise ClobberRefused(f"{n.out} exists and wasn't generated by this script")
        old = dest.read_text(encoding="utf-8") if dest.exists() else None
        if old != text:
            changed.append(("M" if old else "A", str(n.out)))
            if not args.check:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(text, encoding="utf-8")
                wrote += 1

    # Delete our own stale output (vault note renamed, removed, or de-manifested).
    keep = {REPO / n.out for n in notes}
    scope = [docs_root / s["slug"] for s in cfg["section"] if not args.section or s["slug"] in args.section]
    for d in scope:
        for old in d.glob("*.md") if d.exists() else []:
            if old not in keep and is_ours(old):
                changed.append(("D", str(old.relative_to(REPO))))
                if not args.check:
                    old.unlink()

    if not args.check:
        assets.flush(rep)
    nav_changed = splice_nav(build_nav(notes, cfg, args.section), args.check)

    # Report.
    for w in rep.warnings:
        print(f"warn: {w}", file=sys.stderr)
    if rep.skipped_empty:
        print(f"\nskipped {len(rep.skipped_empty)} empty note(s): "
              f"{', '.join(Path(p).name for p in rep.skipped_empty)}", file=sys.stderr)
    if rep.dead_links and args.verbose:
        print("\ndead links (degraded to plain text):", file=sys.stderr)
        for d in rep.dead_links:
            print(f"  {d}", file=sys.stderr)
    elif rep.dead_links:
        print(f"\n{len(rep.dead_links)} dead link(s) degraded to plain text (--verbose to list)",
              file=sys.stderr)

    if args.check:
        for kind, p in changed:
            print(f"{kind} {p}")
        if nav_changed:
            print("M mkdocs.yml (nav)")
        if changed or nav_changed:
            print(f"\n{len(changed)} file(s) out of sync — run without --check", file=sys.stderr)
            return 1
        print("in sync")
        return 0

    print(f"\n{len(notes)} note(s) published, {wrote} written, "
          f"{len(assets.copies)} image(s) copied")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except PolicyViolation as e:
        print(f"\nPOLICY VIOLATION — nothing written.\n  {e}", file=sys.stderr)
        sys.exit(2)
    except ClobberRefused as e:
        print(f"\nREFUSED — nothing written.\n  {e}\n  Use --force to overwrite.", file=sys.stderr)
        sys.exit(3)
